# Generated by Django 4.2.5 on 2023-10-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('heading_1', models.CharField(max_length=200)),
                ('heading_1_content', models.CharField(max_length=5000)),
                ('sub_heading_1', models.CharField(max_length=200)),
                ('sub_heading_1_content', models.CharField(max_length=5000)),
                ('heading_2', models.CharField(max_length=200)),
                ('heading_2_content', models.CharField(max_length=5000)),
                ('sub_heading_2', models.CharField(max_length=200)),
                ('sub_heading_2_content', models.CharField(max_length=5000)),
                ('heading_3', models.CharField(max_length=200)),
                ('heading_3_content', models.CharField(max_length=5000)),
                ('sub_heading_3', models.CharField(max_length=200)),
                ('sub_heading_3_content', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='blog/images')),
            ],
        ),
    ]
