# Generated by Django 4.2.5 on 2023-09-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_product_category_product_prod_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('phone', models.CharField(default='', max_length=15)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.TextField(max_length=700),
        ),
    ]
