# Generated by Django 4.2.5 on 2023-10-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_orders_item_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=6000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
